create table worker (
  id int primary key generated by default as identity
  , first_name varchar(128)
  , last_name varchar(128)
  , profile_picture varchar(128)
);

create table worked_hour (
  id int primary key generated by default as identity
  , worker_id int constraint fk_worked_hour__worker_id__references__worker__id references worker
  , day date
  , hours int
  , hourly_wage decimal(5, 2)
);
